displayName: Response Body Rewrite

summary: Middleware with ability to replace response body with with regex

type: middleware

import: github.com/the-ccsn/traefik-plugin-rewritebody

testData:
  lastModified: true
  rewrites:
    - regex: "bar"
      replacement: "foo"
  monitoring:
    types:
      - text/html
    methods:
      - GET
    checkMimeAccept: true
    checkMimeContentType: true
    checkAcceptEncoding: true
    checkContentEncoding: true
